#name: Update readme
#
#on:
#  schedule:
#    - cron: "0 4 * * *"
#  workflow_dispatch:
#
#jobs:
#  readme:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v3
#        with:
#          node-version: 16
#      - run: npm install
#
#      - name: Get weather data
#        env:
#          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
#          CITY: "1835848" # Seoul
#        run: |
#          curl -s "http://api.openweathermap.org/data/2.5/weather?id=${CITY}&appid=${WEATHER_API_KEY}"
#
#      - name: Generate readme
#        env:
#          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
#        run: node build-svg.js
#
#      - name: Commit changes
#        uses: EndBug/add-and-commit@v4
#        with:
#          author_name: GeonWoo Lee
#          author_email: thisiswoo0594@gmail.com
#          message: "Auto updating my readme"
#          add: "*.svg"
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Update Weather in README

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install openweather-apis js-quantities

      - name: Update README with weather
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }} # GitHub Secrets에 API 키 저장
        run: node build-svg.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: GeonWoo Lee
          author_email: thisiswoo0594@gmail.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}